---
- name: Automate RHEL KVM Kubernetes Cluster Setup
  hosts: all
  gather_facts: no
  vars_files:
    - ../vars/all.yml  # Load all variables from the central file

- name: Setup RHEL KVM Host
  hosts: kvm_host
  become: yes
  roles:
    - role: kvm_host_setup

- name: Create Kubernetes VMs on KVM host
  hosts: kvm_host
  become: yes
  roles:
    - role: vm_creation

- name: Wait for VMs to be reachable via SSH
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 5
        timeout: 300

- name: Prepare VMs for Kubernetes installation
  hosts: k8s_nodes
  become: yes
  roles:
    - role: k8s_prereqs

- name: Initialize Kubernetes Control Plane
  hosts: k8s_control_plane
  become: yes
  roles:
    - role: k8s_control_plane

- name: Join Worker Nodes to the cluster
  hosts: k8s_workers
  become: yes
  roles:
    - role: k8s_worker_join