---
- name: Initialize the Kubernetes control plane
  ansible.builtin.shell: >
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} --apiserver-advertise-address={{ ansible_host }}
  register: kubeadm_init_output

- name: Wait for control plane to be ready
  ansible.builtin.shell: "kubectl get pods --all-namespaces"
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout.find("kube-flannel") != -1
  retries: 20
  delay: 10

- name: Setup kubectl config
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    creates: "$HOME/.kube/config"

- name: Install a Pod Network (Flannel)
  ansible.builtin.shell: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"

- name: Generate and save the join command
  ansible.builtin.shell: "kubeadm token create --print-join-command"
  register: join_command
  
- name: Copy join command to a local file
  ansible.builtin.copy:
    content: "{{ join_command.stdout }}"
    dest: "/tmp/kube_join_command.sh"
    mode: '0755'
  delegate_to: localhost
